### PR TITLE
DID test fixtures and regex escaping fixes

### PR DESCRIPTION
**Pull request by anweiss**
Addresses #67.

@jonnycrunch FYI I'm adding a bunch of test fixtures based on https://github.com/w3c/did-spec-registries/pull/138.

### CODE REVIEW

**Comment by jonnycrunch** [comment]
nice!  Thanks!

**Comment by anweiss** [comment]
@jonnycrunch I have added all of your [proposed](https://ipfs.io/ipfs/Qmc9Zf5WigJQ7gcxHqpZZDcwMpFur5c5fSEhSykmWipPUH) CDDL DID definitions as text fixtures to this crate and all of the known good documents are validating successfully. The known bad documents are also failing to validate as expected. I managed to squash a few parser and validation bugs thanks to your examples. So much appreciated!

Below is my list of findings:

- `capabilityDelegation.cddl` has a typo on Line 3 ... should be `capabilityDelegation` and not `capabilityDelgation`
- `example2.json` is missing a `controller` key (you [mentioned](https://github.com/w3c/did-spec-registries/pull/138#issuecomment-719737667) you would remove this file anyways)
- if `service_example1.json` is supposed to validate against `service.cddl`, it will fail because the root type is `did-document` not `serviceEndpoint`
- typo in `serviceEndpoint.cddl` ... should be `serviceEndpoint` and not `serivceEndpoint`

**Comment by jonnycrunch** [comment]
@anweiss  Many thanks!  I'm working on updating the examples.

**Comment by jonnycrunch** [comment]
regarding service.cddl , good catch!  I owe you a beer!  update pending.

**Pull request merged**
