### PR TITLE
API improvements

### PR DESCRIPTION
**Pull request by anweiss**
Addresses #105 and #114

### CODE REVIEW

**Comment by itamarst** [comment]
I can probably create a branch off of your branch, will try that.

**Comment by itamarst** [comment]
That is, create a branch of `pycddl` that uses branch of `cddl`, to try the new API.

**Comment by itamarst** [comment]
I tested `CDDL::from_slice` with my current approach of parsing the schema for every validation. It works, simplified the code slightly.

**Comment by itamarst** [comment]
For reference, here's the branch using this branch: https://gitlab.com/tahoe-lafs/pycddl/-/blob/12-persistent-schema-instead-of-parsing-schema-on-each-validation/src/lib.rs

**Comment by anweiss** [comment]
Thanks for testing! Yea, I'll be working through #104 once I get this PR finished up.

**Pull request merged**
